const songLyrics = {
    1: [
        { time: 0, text: "本当は私気づいてたんです" },
        { time: 3, text: "あなたが私を見ていてくれたこと" },
        { time: 12, text: "Alright, alright, whoa" },
        { time: 14, text: "Why you pointing at me with that knife?" },
        { time: 17, text: "I've been cutting corners all my life, girl" },
        { time: 20, text: "The terror doesn't blossom overnight, no" },
        { time: 23, text: "She's running through the city in a rampage" },
        { time: 26, text: "Pressing on her fingers 'til the bones break" },
        { time: 29, text: "There's blood all in her nose from the propane" },
        { time: 32, text: "But a needle to the skin will make the pain fade" },
        { time: 34, text: "Yeah, ah-ah" },
        { time: 36, text: "This is what I do, ah-ah" },
        { time: 39, text: "Take another bite, ah-ah" },
        { time: 42, text: "Big enough to chew" },
        { time: 46, text: "She said, 'Careful, or you'll lose it'" },
        { time: 49, text: "But, girl, I'm only human" },
        { time: 52, text: "And I know there's a blade where your heart is" },
        { time: 55, text: "And you know how to use it" },
        { time: 58, text: "And you can take my flesh if you want, girl" },
        { time: 61, text: "But, baby, don't abuse it" },
        { time: 64, text: "These voices in my head screaming, 'Run, now'" },
        { time: 67, text: "I'm praying that they're human" },
        { time: 69, text: "Rollin', rollin"}, 
       { time: 72, text: "rolling back your eyes through your mind like" },
        { time: 75, text: "Oh, whoa, the pressure in the gland's tight" },
        { time: 81, text: "Yeah, whoa, it's either kill or be killed" },
        { time: 87, text: "Oh, whoa, the blood is either poured or it's spilt" },
        { time: 92, text: "Yeah, ah-ah, This is what I do" },
        { time: 97, text: "Take another bite, ah-ah" },
        { time:101 , text: "Big enough to chew" },
        { time: 104, text: "She said, 'Careful, or you'll lose it'" },
        { time: 107, text: "But, girl, I'm only human" },
        { time: 110, text: "And I know there's a blade where your heart is" },
        { time: 113, text: "And you know how to use it" },
        { time: 116, text: "And you can take my flesh if you want, girl" },
        { time: 119, text: "But, baby, don't abuse it" },
        { time: 122, text: "These voices in my head screaming, 'Run, now'" },
        { time: 124, text: "I'm praying that they're human" },
        { time: 128, text: "Alright, alright, whoa" },
        { time: 130, text: "Love you but you cannot spend the night" },
        { time: 133, text: "Nah, I've been alone almost all my life, girl" },
        { time: 135, text: "And shit like that don't change up overnight, sweet" },
        { time: 140, text: "I let you sleep in my tee (tee)" },
        { time: 141, text: "Tell me the things that you don't normally tweet" },
        { time: 144, text: "Acid and LSD and smokin' blunts on the beach" },
        { time: 147, text: "69 down 69, so we can both get a piece" },
        { time: 150, text: "I've been cutting corners like my whole life" },
        { time: 153, text: "Backstabbing bitches tryna kill me" },
        { time: 156, text: "Day I die'll be the only day a nigga ghostwrite" },
        { time: 158, text: "When I go, they'll treat me like a god" },
        { time: 162, text: "She said, 'Careful, or you'll lose it'" },
        { time: 165, text: "But, girl, I'm only human" },
        { time: 168, text: "And I know there's a blade where your heart is" },
        { time: 171, text: "And you know how to use it" },
        { time: 174, text: "And you can take my flesh if you want, girl" },
        { time: 176, text: "But, baby, don't abuse it" },
        { time: 179, text: "These voices in my head screaming, 'Run, now'" },
        { time: 182, text: "I'm praying that they're human" },
        { time: 184, text: "Please understand that I'm trying my hardest" },
        { time: 186, text: "My head's a mess, but I'm trying regardless" },
        { time: 191, text: "Anxiety is one hell of a problem" },
        { time: 194, text: "She's latching onto me, I can't resolve it" },
        { time: 197, text: "It's not right, it's not fair..." },
        { time: 203, text: "It's no fair, it's no fair" },
        { time: 206, text: "Oh, no, no, no..." },
        { time: 215, text: "Don't run, don't run" }
    ]
};
